### ISSUE TITLE
Parse SDK 1.3.1 and Retrofit 2.1.0 do not work together

### ISSUE THREAD

**Issue by nickaein-a** [ParsePlatform/Parse-SDK-Android#531]
ParseInstallation won't save after upgrading retrofit to 2.1.0. 
i can see deviceToken in LogCat but i can't find it in ParseDashboard
logcat:
```
V/com.parse.GcmRegistrar: Received deviceToken <APA91bE0u2Sg1LMJciAyGXrxN3wWbecnx8ouVfsvUDIVDFy8GGibtqz1bJZmEGZwc9-a9mc9W3z_NEDpaOiM60Byp_nGgylj7x0c8A7qUX8anuKcxig9Re895SyEPXfniTTlbBdM4bGk> from GCM.
E/Parse: Installation failed to save: com.parse.ParseException: java.lang.NullPointerException: value == null

```
ParseLogIntercepter shows nothing
and when i use latest jar:
```
NoClassDefFoundError: Failed resolution of: Lbolts/Task;
at com.parse.Parse.initialize(Parse.java:414)
```

Parse 1.3.0 still works

**Comment by grantland** [comment]
Unfortunately this is not something we're going to support.

**Comment by muetzenflo** [comment]
that's the spirit...
