### ISSUE TITLE
Application crashes On android 4.4.x and below.

### ISSUE THREAD

**Issue by Ethan-Velosys** [ParsePlatform/Parse-SDK-Android#342]
All of this code works on Android 5.0 and up.
I'm using Parse version 1.12.0

Here is my stack trace. It crashes on the first attempt to register a subclass of parseobject.

              01-13 12:18:26.500 1347-1347/? E/AndroidRuntime: FATAL EXCEPTION: main
             java.lang.NoClassDefFoundError: com.parse.ParseObject$1
                 at com.parse.ParseObject.<clinit>(ParseObject.java:316)
                 at com.company.myapp.utils.Application.onCreate(PensterApplication.java:36)
                 at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                 at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4444)
                 at android.app.ActivityThread.access$1300(ActivityThread.java:141)
                 at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1316)
                 at android.os.Handler.dispatchMessage(Handler.java:99)
                 at android.os.Looper.loop(Looper.java:137)
                 at android.app.ActivityThread.main(ActivityThread.java:5103)
                 at java.lang.reflect.Method.invokeNative(Native Method)
                 at java.lang.reflect.Method.invoke(Method.java:525)
                 at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
                 at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
                 at dalvik.system.NativeStart.main(Native Method)

Here is the Application class where it crashes.
I've altered the class names to post online here

      public class myApplication extends Application {
            @Override
            public void onCreate() {
                super.onCreate();
                FacebookSdk.sdkInitialize(this);

                // Enable Local Datastore.
                Parse.enableLocalDatastore(this);

                // Parse classes that need registering
                ParseObject.registerSubclass(aaa.class); //error happens here
                ParseObject.registerSubclass(bbb.class);
                ParseObject.registerSubclass(ccc.class);
                ParseObject.registerSubclass(ddd.class);
                ParseObject.registerSubclass(eee.class);
                ParseObject.registerSubclass(fff.class);
                ParseObject.registerSubclass(ggg.class);
                ParseObject.registerSubclass(hhh.class);
                ParseObject.registerSubclass(iii.class);
                ParseObject.registerSubclass(jjj.class);
                Parse.initialize(this, PARSE_APPLICATION_ID, PARSE_CLIENT_KEY);

                //set a default acl so that default is not public read.write
                if (ParseUser.getCurrentUser() != null) {
                    ParseACL defaultACL = new ParseACL(ParseUser.getCurrentUser());
                    defaultACL.setPublicReadAccess(false);
                    defaultACL.setPublicWriteAccess(false);
                    ParseACL.setDefaultACL(defaultACL, true);
                }

                // Save this installation
                ParseInstallation.getCurrentInstallation().saveInBackground();
                ParseFacebookUtils.initialize(this);
                ParseTwitterUtils.initialize(TWITTER_CONSUMER_KEY, TWITTER_CONSUMER_SECRET);

            }
        }

**Comment by grantland** [comment]
Could you attempt doing a clean build? It seems like something funky is going on with your environment if this line is failing: https://github.com/ParsePlatform/Parse-SDK-Android/blob/1.12.0/Parse/src/main/java/com/parse/ParseObject.java#L316

**Comment by Rhadammanthis** [comment]
I am having the exact same issue. Already cleaned and built but nothing seems to change.

**Comment by Ethan-Velosys** [comment]
I tried the clean and build as well, but to no avail. 
I also tried downloading the Example project from parse and running it locally to see if there was an issue with my compiler or something, and the example had no problems. So it seems like the issue is somewhere in my project.
I have also tried 
AndroidStudio --> Close and Invalidate caches, 
disabling proguard, 
and building from a different machine.

I also posted the issue on stack overflow. Here is a link.
http://stackoverflow.com/questions/34779403/noclassdeffounderror-com-parse-parseobject1

**Comment by Rhadammanthis** [comment]
My code is virtually the sames as that of@Ethan-Velosys . Some calls to `ParseObject.registerSubclass()` and then `Parse.initialize()`. The code crashes at the first instance of `ParseObject.registerSubclass()`. 

I tested my app in Lollipop (5.1) and worked just fine but it wasn't until testing on KitKat (4.2) that the error appeared.

Here is the stack trace:

`    java.lang.VerifyError: com/parse/ParseObject
            at com.dacompsc.liturguiaandroid.LiturguiaApplication.onCreate(LiturguiaApplication.java:83)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1017)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4579)
            at android.app.ActivityThread.access$1400(ActivityThread.java:154)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:137)
            at android.app.ActivityThread.main(ActivityThread.java:5306)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:511)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1102)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:869)
            at dalvik.system.NativeStart.main(Native Method)`

The logcast also logs this:

` E/dalvikvm﹕ Could not find class 'com.parse.ParseObject$1', referenced from method com.parse.ParseObject.<clinit>`
`E/dalvikvm﹕ Could not find class 'com.parse.TaskQueue', referenced from method com.parse.ParseObject.<init>`
`Could not find class 'com.parse.ParseObject$37', referenced from method com.parse.ParseObject.canBeSerialized`
`E/dalvikvm﹕ Could not find class 'com.parse.ParseObject$36', referenced from method com.parse.ParseObject.collectDirtyChildren`
`E/dalvikvm﹕ Could not find class 'com.parse.ParseObject$4', referenced from method com.parse.ParseObject.collectFetchedObjects`
`E/dalvikvm﹕ Could not find class 'com.parse.ParseOperationSet', referenced from method com.parse.ParseObject.currentOperations`

**Comment by grantland** [comment]
Could both of you show me your `build.gradle` files? Also, would either of you be using multidex?

@Ethan-Velosys Have you tried decompiling your application to see if those classes actually exist?

@Rhadammanthis Your issue seems slightly different as the error is not the same. Do you have proguard enabled and have you tried disabling it? Is this also occurring on 1.12.0 or another SDK version?

**Comment by grantland** [comment]
If you have multidex enabled, #213 might be relevant.

**Comment by Rhadammanthis** [comment]
@grantland it works now! I used the solution in #213 and it now works like a charm. Thank you!

**Comment by grantland** [comment]
Awesome! I'll be closing this issue then.

@Rhadammanthis if #213 doesn't solve your issue, it's different and I'd suggest opening a new issue.

**Comment by Ethan-Velosys** [comment]
Thank you! This solved it for me as well.
